server:
  port: 8081
# mysql??
spring:
  rabbitmq:
    host: 49.233.52.137
    port: 5673
    username: admin
    password: admin
    virtual-host: test
    listener:
      direct:
        acknowledge-mode: none
    connection-timeout: 0
    #确认消息已发送到交换机(Exchange)回调
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)回调
    publisher-returns: true
  application:
    name: cosFileTest
  datasource:
    url: mysql://49.233.52.137:3306/test?serverTimezone=GMT%2B8
    username: root
    password: Temp123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
#COS对象存储参数配置
tencent:
  cos:
    secretId:
    secretKey:
    buckerName: test-1314885658
    region: ap-chengdu
    url: test-1314885658.cos.ap-chengdu.myqcloud.com


